M48
; DRILL file {KiCad (6.0.8-1)-1} date 2023 January 08, Sunday 15:16:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-08T15:16:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X163.78Y-59.3
X236.22Y-40.64
X236.22Y-83.82
T0
M30
